from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import text
from sqlmodel import Session, SQLModel, create_engine, select


BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / ".env", override=True)

from app.config import settings
import app.models  # noqa: F401
from app.models.department import Department


database_url = settings.database_url
engine = create_engine(database_url, echo=False)
website_engine = (
    create_engine(settings.website_database_url, echo=False)
    if settings.website_database_url
    else None
)
DEFAULT_DEPARTMENTS = (
    ("Human Resources (HR)", "Recruitment, people operations, talent management, and employee support."),
    ("Information Technology (IT) & Software Development", "Software engineering, systems administration, ERP, BI, SAP, web, and platform delivery."),
    ("Engineering", "Technical engineering disciplines, design, production, and infrastructure delivery."),
    ("Product", "Product strategy, roadmap ownership, discovery, delivery coordination, and user value optimization."),
    ("Data", "Analytics, business intelligence, reporting, data engineering support, and data-driven decision making."),
    ("Operations", "Operational execution, process coordination, service continuity, and cross-functional workflow improvement."),
    ("Supply Chain & Procurement", "Procurement, sourcing, logistics, inventory, and supply chain analysis."),
    ("Marketing & Digital Marketing", "Brand, content, SEO, PPC, social media, design, and digital growth initiatives."),
    ("Sales & Business Development", "Revenue generation, account growth, partnerships, and commercial development."),
    ("Finance & Accounting", "Financial planning, controlling, bookkeeping, reporting, and accounting operations."),
    ("Administration & Operations", "Office administration, internal operations, coordination, and business support."),
    ("Project Management", "Project planning, delivery governance, stakeholder management, and execution oversight."),
    ("Customer Support", "Client support, service operations, onboarding, and issue resolution."),
)


def ensure_website_jobs_table() -> None:
    if website_engine is None:
        return

    with website_engine.begin() as connection:
        connection.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS public.jobs_infos (
                    job_info_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    location VARCHAR(255) NOT NULL,
                    type VARCHAR(100) NOT NULL,
                    content TEXT,
                    pdf_url TEXT,
                    hr_vacancy_id INTEGER,
                    published SMALLINT NOT NULL DEFAULT 0,
                    created_by INTEGER NOT NULL,
                    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW()
                )
                """
            )
        )
        connection.execute(
            text(
                """
                ALTER TABLE public.jobs_infos
                ADD COLUMN IF NOT EXISTS title VARCHAR(255),
                ADD COLUMN IF NOT EXISTS location VARCHAR(255),
                ADD COLUMN IF NOT EXISTS type VARCHAR(100),
                ADD COLUMN IF NOT EXISTS content TEXT,
                ADD COLUMN IF NOT EXISTS pdf_url TEXT,
                ADD COLUMN IF NOT EXISTS hr_vacancy_id INTEGER,
                ADD COLUMN IF NOT EXISTS published SMALLINT DEFAULT 0,
                ADD COLUMN IF NOT EXISTS created_by INTEGER,
                ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) DEFAULT NOW(),
                ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT NOW()
                """
            )
        )
        connection.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS idx_jobs_infos_created_at
                ON public.jobs_infos (created_at DESC)
                """
            )
        )
        connection.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS idx_jobs_infos_published
                ON public.jobs_infos (published)
                """
            )
        )


def ensure_candidate_resume_storage() -> None:
    with engine.begin() as connection:
        connection.execute(
            text(
                """
                ALTER TABLE candidate
                ADD COLUMN IF NOT EXISTS resume_file_name VARCHAR(255),
                ADD COLUMN IF NOT EXISTS resume_content_type VARCHAR(100),
                ADD COLUMN IF NOT EXISTS resume_file_checksum VARCHAR(64),
                ADD COLUMN IF NOT EXISTS resume_file_data BYTEA
                """
            )
        )
        connection.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS ix_candidate_resume_file_checksum
                ON candidate (resume_file_checksum)
                """
            )
        )
        connection.execute(
            text(
                """
                ALTER TABLE parse_jobs
                ADD COLUMN IF NOT EXISTS file_checksum VARCHAR(64),
                ADD COLUMN IF NOT EXISTS file_blob_data BYTEA
                """
            )
        )
        connection.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS ix_parse_jobs_file_checksum
                ON parse_jobs (file_checksum)
                """
            )
        )


def get_session():
    with Session(engine) as session:
        yield session


def ensure_default_departments(session: Session) -> None:
    existing_departments = session.exec(select(Department)).all()
    existing_by_name = {department.name.strip().lower(): department for department in existing_departments if department.name}
    changed = False

    for name, description in DEFAULT_DEPARTMENTS:
        normalized_name = name.strip().lower()
        department = existing_by_name.get(normalized_name)
        if department is None:
            session.add(Department(name=name, description=description))
            changed = True
            continue
        if not department.description and description:
            department.description = description
            session.add(department)
            changed = True

    if changed:
        session.commit()


def init_db() -> None:
    SQLModel.metadata.create_all(engine)
    ensure_website_jobs_table()
    ensure_candidate_resume_storage()

    with Session(engine) as session:
        ensure_default_departments(session)
